[PREFIX_TO_SHEET]
SR-ADI 1 	=	IRC ZN
SR-ADM KTR 	=	IRC ZN
SR-AGUS 	=	IRC ZN
SR-AGUS 1 	=	IRC ZN
SR-AGUS SULISTIONO 	=	IRC ZN
SR-ALBERTUS 	=	IRC ZN
SR-ARIS 	=	IRC ZN
SR-BETA 	=	IRC ZN
SR-BETA 1 (FRAUD DIDI) 	=	IRC ZN
SR-CHRISTIAN (FRAUD) 	=	IRC ZN
SR-COUNTER  	=	IRC ZN
SR-DANIEL (FRAUD) 	=	IRC ZN
SR-DEDY (FRAUD) 	=	IRC ZN
SR-DHONI (FRAUD) 	=	IRC ZN
SR-DWI IRC 	=	IRC ZN
SR-DWI OLI 	=	IRC ZN
SR-ENDI 	=	IRC ZN
SR-FAJAR 	=	IRC ZN
SR-HANDOYO 1 	=	IRC ZN
SR-HELMI 	=	IRC ZN
SR-JIMMY  	=	IRC ZN
SR-JM AFIFAH 	=	IRC ZN
SR-JM ARI 	=	IRC ZN
SR-JM ARIS 	=	IRC ZN
SR-JM AZIZ 	=	IRC ZN
SR-JM BHARI 	=	IRC ZN
SR-JM DANU 	=	IRC ZN
SR-JM TEGUH 	=	IRC ZN
SR-JOKO 1 	=	IRC ZN
SR-JOKO 2 (FRAUD CHANDRA) 	=	IRC ZN
SR-JOKO 3 (FRAUD PANDU) 	=	IRC ZN
SR-JOKO 4 (FRAUD RIO) 	=	IRC ZN
SR-JOKO 5 	=	IRC ZN
SR-JOKO 6 (FRAUD DENI) 	=	IRC ZN
SR-JOKO 7 (FRAUD DANA) 	=	IRC ZN
SR-KHOLIS 	=	IRC ZN
SR-ROFII (FRAUD) 	=	IRC ZN
SR-SUGI 	=	IRC ZN
SR-SUHAR (FRAUD) 	=	IRC ZN
SR-TITIS (FRAUD) 	=	IRC ZN
SR-WAHYU 	=	IRC ZN
SR-YUDHI 	=	IRC ZN
SR-YUSTUS 	=	IRC ZN

[PRODUCT_FILTERS]
COLUMN_NAME = Nama Kontak
KEYWORDS = IRC, ZN

[JT]
Aktif = YES